### ISSUE TITLE
Motordriver aansturen.

### ISSUE THREAD

**Issue by Gibi500** [vives-project-xp/GoBabyGo2.0#14]

**Comment by RobbeDeW** [comment]
Aan de hand van de esp8266 willen we een motor laten draaien a.d.h.v een driver(L298N)

**Comment by RobbeDeW** [comment]
Info van de driver in de ReadMe gezet.

**Comment by RobbeDeW** [comment]
Nog kleine aanpassingen gedaan aan het aansluitschema van de driver.
