### ISSUE TITLE
Aandrijving aansturen

### ISSUE THREAD

**Issue by Gibi500** [vives-project-xp/GoBabyGo2.0#17]

**Comment by RobbeDeW** [comment]
We laten de auto vooruit en achteruit rijden a.d.h.v een joystick. Dit wordt gedaan met een ESP8266 we zullen dan later nog overschakelen naar een ESP32.

**Comment by RobbeDeW** [comment]
Aangezien het deel van de potmeter niet meer wordt uitgevoerd worden zijn we hier klaar mee
