### ISSUE TITLE
Wielen regelen zodat ze standaard rechtdoor staan.

### ISSUE THREAD

**Issue by Gibi500** [vives-project-xp/GoBabyGo2.0#41]
Probleem: De wielen kunnen standaard op een hoek staan door tolerantie van de auto.

Is het mogelijk om op te lossen in software of hardware of iets anders...

**Comment by Gibi500** [comment]
We kunnen een trim potentiometer in serie zetten met de potentiometer van de stuur. Er kan dan gewoon in software de waarde waar de stuur wilt gaan  voor centerpositie aan passen aan de nieuwe schakeling.

Het kan dat dit niet werkt doordat de wielen te los staan waardoor de wielen nooit "recht" kunnen staan.

Maar we kunnen dat pas maar uittesten als we het proberen...

**Comment by RobbeDeW** [comment]
Vanwege de beperkte beweging van de wielenstang kunnen we deze niet nauwkeurig meten met een potentiometer. Na overleg met de leerkrachten hebben we gezocht naar alternatieve oplossingen. Helaas zijn we gezamenlijk tot de conclusie gekomen dat het met de beschikbare tijd niet haalbaar is om dit aspect van ons project te realiseren. Daarom hebben we besloten om dit deel van ons project te laten vervallen.
